server:
  port: 8088

spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 5
      min-idle: 5
      initial-size: 5
      max-wait-millis: 1000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 1880
    tomcat:
      max-wait: 1000
      max-active: 100
  jackson:
    time-zone: GMT+8
  boot:
    admin:
      client:
        url: http://localhost:8089/miji/monitor
        username: miji
        password: mijiservermonitor
        instance:
          metadata:
            user.name: miji
            user.password: mijiservermonitor
  application:
    name: miji-server
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mijimemo.server.entity
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: ./logs/log
  level:
    root: info
